### PR TITLE
Add CaraMelSwap & Put in Alphabetical Order

### PR DESCRIPTION
**Pull request by matbrgz**

### CODE REVIEW

**Comment by juan-silveira** [comment]
Sorry, I didn't updated this repo with my last commits to the main server, I already did the Alphabetical Order at the running version.

So I will decline this merge, and I'll update my last commit, and then you can send your PR again, ok?

**Comment by juan-silveira** [comment]
Please, perform your PR after this new update that I just did.

**Comment by matbrgz** [comment]
Ok Close this and then i will open other. Porque estamos falando ingles :P

**Comment by juan-silveira** [comment]
It has to be in english to help other communities.

**Pull request closed without merging**
